services:
    web:
        container_name: web
        build:
            context: ./web
        ports:
            - "80:80"

    server:
        container_name: server
        build:
            context: ./server
        ports:
            - "3000:3000"
        environment:
            - HOST=0.0.0.0
            - OLLAMA_MODEL=llama3.1
            - OLLAMA_URL=http://ollama:11434
            - CHROMA_URL=http://chroma:8000
            - POSTGRES_HOST=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres_pwd
            - POSTGRES_DB=chatdb
        depends_on:
            - ollama
            - postgres
            - chroma

    ollama:
        image: ollama/ollama:0.3.14
        container_name: ollama
        volumes:
            - ollama:/root/.ollama

    chroma:
        image: chromadb/chroma:0.5.15
        container_name: chroma
        environment:
            - IS_PERSISTENT=TRUE
        volumes:
            - chroma:/chroma/chroma

    postgres:
        image: postgres:17-alpine
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres_pwd
            - POSTGRES_DB=chatdb
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    ollama:
    postgres:
    chroma:
