name: mobile
description: A new Flutter project.
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  showcaseview: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_html: ^2.2.1
  flutter_markdown: ^0.6.10
  http: ^1.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Manrope-VariableFont_wght
      fonts:
        - asset: fonts/Manrope-VariableFont_wght.ttf
  uses-material-design: true


